# Generated by Django 5.2.4 on 2025-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
